import React, { useEffect, useState, useRef } from "react";
import { useSelector } from "react-redux";
import { Alert, Button, Card } from "react-bootstrap";
import { Page } from "../components/Page";
import { UploadCSV } from "../components/UploadCSV";
import { FirstAnalysisGraphs } from "../components/FirstAnalysisGraphs";
import { SecondAnalysisGraphs } from "../components/SecondAnalysisGraphs";
import { ThirdAnalysisGraphs } from "../components/ThirdAnalysisGraphs";

export const CSV_Input = () => {
  const [showFirstAnalysis, setShowFirstAnalysis] = useState(true);
  const [showSecondAnalysis, setShowSecondAnalysis] = useState(false);
  const [showThirdAnalysis, setShowThirdAnalysis] = useState(false);
  const stateCSV = useSelector((stateCSV) => stateCSV.nlpProcess);
  useEffect(() => {
    console.log(stateCSV);
  })

  return (
    <div className="bg-light">
      <Page title="CSV Input">
        <div style={{ textAlign: "center" }}>
          {/* check if file has been loaded */}
          {stateCSV["loading"] === true && (
            <h4>Loading...</h4>
          )}
          {stateCSV["analysisCompleted"] === false && (
            <div>
              <h2>Select a CSV File to Analyze</h2>
              <hr className="border border-dark" />
              <p>
                Select a CSV File that was generated by the Scopus™ Database to
                perform a PySurveillance Analysis.
              </p>
              <UploadCSV />
              <hr className="border border-dark" />
            </div>
          )}

        </div>
      </Page>
    </div>
  );
};
