import React, { useState} from "react";
import { useSelector } from "react-redux";
import { Alert, Button, Col, Container, Row, Spinner } from "react-bootstrap";
import { Page } from "../components/Page";
import { UploadCSV } from "../components/UploadCSV";
import { FirstAnalysisGraphs } from "../components/FirstAnalysisGraphs";
import { SecondAnalysisGraphs } from "../components/SecondAnalysisGraphs";
import { ThirdAnalysisGraphs } from "../components/ThirdAnalysisGraphs";

export const CsvInput = () => {
  const [showFirstAnalysis, setShowFirstAnalysis] = useState(true);
  const [showSecondAnalysis, setShowSecondAnalysis] = useState(false);
  const [showThirdAnalysis, setShowThirdAnalysis] = useState(false);

  const nlpState = useSelector((nlpState) => nlpState.nlpProcess);

  return (
    <div className="bg-light">
      <Page title="CSV Input">
        <Container fluid>
          {/* check if file has been loaded */}
          {nlpState["loading"] === true && (
            <Row className="justify-content-center">
              <h4>Performing Analysis...</h4>
              <Spinner animation="border" variant="info" />
            </Row>
          )}
          {nlpState["analysisCompleted"] === false && (
            <Row className="justify-content-center">
              <h2>Select a CSV File to Analyze</h2>
              <h5>
                Select a CSV File that was generated by the Scopus™ Database to
                perform a PySurveillance Analysis.
              </h5>
              <UploadCSV />
            </Row>
          )}
          {nlpState["analysisCompleted"] === true && (
            <div>
              <Row className="justify-content-center">
                <h2 className="text-success">Analysis Completed</h2>
              </Row>
              <hr className="border-secondary" />
              <Row className="justify-space-around">
                <Col>
                  <h5>
                    Number of Scientific Papers in File:{" "}
                    {nlpState.results_before}
                  </h5>
                </Col>
                <Col>
                <h5>Number of Scientific Papers after NLP:{" "}
                    {nlpState.results_after}</h5>
                </Col>
              </Row>
              <hr className="border-secondary" />
              <Row className="justify-content-center">
                <Col>
                  <h3>Show/Hide Graphs</h3>
                </Col>
              </Row>

              <Row className="justify-content-center">
                <Col>
                  {showFirstAnalysis === true && (
                    <Button
                      onClick={() => setShowFirstAnalysis(false)}
                      variant="outline-danger"
                    >
                      Hide First Analysis Graphs
                    </Button>
                  )}
                  {showFirstAnalysis === false && (
                    <Button
                      onClick={() => setShowFirstAnalysis(true)}
                      variant="outline-success"
                    >
                      Show First Analysis Graphs
                    </Button>
                  )}
                </Col>
                <Col>
                  {showSecondAnalysis === true && (
                    <Button
                      onClick={() => setShowSecondAnalysis(false)}
                      variant="outline-danger"
                    >
                      Hide Second Analysis Graphs
                    </Button>
                  )}
                  {showSecondAnalysis === false && (
                    <Button
                      onClick={() => setShowSecondAnalysis(true)}
                      variant="outline-success"
                    >
                      Show Second Analysis Graphs
                    </Button>
                  )}
                </Col>
                <Col>
                  {showThirdAnalysis === true && (
                    <Button
                      onClick={() => setShowThirdAnalysis(false)}
                      variant="outline-danger"
                    >
                      Hide Third Analysis Graphs
                    </Button>
                  )}
                  {showThirdAnalysis === false && (
                    <Button
                      onClick={() => setShowThirdAnalysis(true)}
                      variant="outline-success"
                    >
                      Show Third Analysis Graphs
                    </Button>
                  )}
                </Col>
              </Row>
              <hr className="border-secondary" />
              <div>
                {showFirstAnalysis === true && (
                  <div>
                    <h3>First-Grade Analysis</h3>
                    <FirstAnalysisGraphs />
                    <Button
                      onClick={() => setShowFirstAnalysis(false)}
                      variant="outline-danger"
                    >
                      Hide First Analysis Graphs
                    </Button>
                  </div>
                )}
              </div>
              <div>
                {showFirstAnalysis === false && (
                  <div>
                    <h3>First-Grade Analysis</h3>
                    <Button
                      onClick={() => setShowFirstAnalysis(true)}
                      variant="outline-success"
                    >
                      Show First Analysis Graphs
                    </Button>
                  </div>
                )}
              </div>
              <hr className="border-secondary" />
              <div>
                {showSecondAnalysis === true && (
                  <div>
                    <h3>Second-Grade Analysis</h3>
                    <SecondAnalysisGraphs />
                    <Button
                      onClick={() => setShowSecondAnalysis(false)}
                      variant="outline-danger"
                    >
                      Hide Second Analysis Graphs
                    </Button>
                  </div>
                )}
              </div>
              <div>
                {showSecondAnalysis === false && (
                  <div>
                    <h3>Second-Grade Analysis</h3>
                    <Button
                      onClick={() => setShowSecondAnalysis(true)}
                      variant="outline-success"
                    >
                      Show Second Analysis Graphs
                    </Button>
                  </div>
                )}
              </div>
              <hr className="border-secondary" />
              <div>
                {showThirdAnalysis === true && (
                  <div>
                    <h3>Third-Grade Analysis</h3>
                    <ThirdAnalysisGraphs />
                    <Button
                      onClick={() => setShowThirdAnalysis(false)}
                      variant="outline-danger"
                    >
                      Hide Third Analysis Graphs
                    </Button>
                  </div>
                )}
              </div>
              <div>
                {showThirdAnalysis === false && (
                  <div>
                    <h3>Third-Grade Analysis</h3>
                    <Button
                      onClick={() => setShowThirdAnalysis(true)}
                      variant="outline-success"
                    >
                      Show Third Analysis Graphs
                    </Button>
                  </div>
                )}
              </div>
              <hr className="border-secondary" />
            </div>
          )}
          <div>
            <Alert variant="dark">
              <strong>Note:</strong> If with NLP there are less than 20 results
              then you should add more words to the filter parameters or erase
              all of them to analyze the entire dataset.
            </Alert>
          </div>
        </Container>
      </Page>
    </div>
  );
};
